### ISSUE TITLE
[Android] The keyboard height obtained by some Android phones is incorrect

### ISSUE THREAD

**Issue by q200892907** [nschairer/keyboard_height_plugin#7]
final height = MediaQuery.of(context).viewInsets.bottom;
The keyboard height obtained by the plug-in is different from the bottom height of Flutter. 
 For example, Huawei mate40 pro

**Comment by q200892907** [comment]
val keypadHeight = screenHeight - r.bottom - getNavigationBarHeight();
chatgpt's answer 
val keypadHeight = screenHeight - r.bottom;

**Comment by q200892907** [comment]
@nschairer Is this library still being maintained?

**Comment by nschairer** [comment]
Yes it is, I will get this all reviewed and merged today. Apologies for the delay.
